ALTER TABLE SALES_HOUSING DROP COLUMN SALE_DATETIME;
ALTER TABLE SALES_HOUSING DROP COLUMN SOURCE_URL;
ALTER TABLE SALES_HOUSING DROP COLUMN BOOK;
ALTER TABLE SALES_HOUSING DROP COLUMN PAGE;
ALTER TABLE SALES_HOUSING DROP COLUMN TRANSFER_DEED_TYPE;
ALTER TABLE SALES_HOUSING DROP COLUMN PROPERTY_TOWNSHIP;
ALTER TABLE SALES_HOUSING DROP COLUMN PROPERTY_LAT;
ALTER TABLE SALES_HOUSING DROP COLUMN PROPERTY_LON;
ALTER TABLE SALES_HOUSING DROP COLUMN DEED_DATE;
ALTER TABLE SALES_HOUSING DROP COLUMN BUILDING_ASSESSED_DATE;
ALTER TABLE SALES_HOUSING DROP COLUMN SELLER_2_NAME;
ALTER TABLE SALES_HOUSING DROP COLUMN LAND_ASSESSED_DATE;
ALTER TABLE SALES_HOUSING DROP COLUMN SELLER_2_STATE;
ALTER TABLE SALES_HOUSING DROP COLUMN BUYER_2_STATE;
ALTER TABLE SALES_HOUSING DROP COLUMN BUYER_2_NAME;

DELETE FROM CLEAN_TABLE_0
WHERE SALE_PRICE < 50000;
DELETE FROM CLEAN_TABLE_0
WHERE TOTAL_ASSESSED_VALUE is NULL;
DELETE FROM CLEAN_TABLE_0
WHERE PROPERTY_ZIP5 = '0';
