INSERT INTO HOUSING_CIS9440.HOUSINGNY.DIM_SALE (SALE_ID, PROPERTY_ZIP5, SALE_PRICE, MIN_SALE_PRICE, MAX_SALE_PRICE, AVG_SALE_PRICE)
WITH ZipCodeStats AS (
    SELECT
        SALE_ID,
        PROPERTY_ZIP5,
        SALE_PRICE,
        MIN(SALE_PRICE) OVER(PARTITION BY PROPERTY_ZIP5) AS MIN_SALE_PRICE,
        MAX(SALE_PRICE) OVER(PARTITION BY PROPERTY_ZIP5) AS MAX_SALE_PRICE,
        ROUND(AVG(SALE_PRICE) OVER(PARTITION BY PROPERTY_ZIP5)) AS AVG_SALE_PRICE
    FROM
        HOUSING_CIS9440.HOUSINGNY.SALES_HOUSING
)
SELECT
    SALE_ID,
    PROPERTY_ZIP5,
    SALE_PRICE,
    MIN_SALE_PRICE,
    MAX_SALE_PRICE,
    AVG_SALE_PRICE
FROM
    ZipCodeStats
WHERE
    SALE_PRICE >= 50000
    AND MIN_SALE_PRICE >= 50000
    AND MAX_SALE_PRICE >= 50000
    AND AVG_SALE_PRICE >= 50000
QUALIFY
    ROW_NUMBER() OVER (PARTITION BY PROPERTY_ZIP5 ORDER BY PROPERTY_ZIP5) = 1;