USE DATABASE HOUSING_CIS9440;
USE SCHEMA HOUSINGNY;

-- Create or replace sequence for generating FACTS_ID
CREATE OR REPLACE SEQUENCE FACTS_ID_SEQUENCE;

-- Insert data into facts_housing using the sequence to generate FACTS_ID
INSERT INTO HOUSING_CIS9440.HOUSINGNY.FACTS_HOUSING (
    FACTS_ID,
    LIVING_WAGE,
    POVERTY_WAGE,
    MINIMUM_WAGE,
    LIVING_EXPENSES,
    TYPICAL_ANNUAL__SALARY,
    PROFESSION_ID,
    LOCATION_ID,
    PUPIL_TEACHER_RATIO,
    SCHOOL_ID,
    POPULATION_NUM,
    INDEX_TOTAL_COUNT,
    VIOLENT_TOTAL_COUNT,
    MURDER_COUNTRAPE_COUNT,
    ROBBERY_COUNT,
    AGGREVATED_ASSAULT_COUNT,
    PROPERTY_TOTAL_COUNT,
    BURGLARY_COUNT,
    LARCENY_COUNT,
    MV_THEFT_COUNT,
    BUILDING_ASSESSED_VALUE,
    BUILDING_APPRAISED_VALUE,
    SALE_PRICE,
    LAND_APPRAISED_VALUE,
    LAND_ASSESSED_VALUE,
    SALE_ID,
    PROPERTY_ID,
    TIME_ID  
)
SELECT
    FACTS_ID_SEQUENCE.NEXTVAL AS FACTS_ID,
    COALESCE(TO_NUMBER(REPLACE(REPLACE("MIT_LIVINGWAGE".LIVING_WAGE, '$', ''), ',', '')), 0) AS LIVING_WAGE,
    COALESCE(TO_NUMBER(REPLACE(REPLACE("MIT_LIVINGWAGE".POVERTY_WAGE, '$', ''), ',', '')), 0) AS POVERTY_WAGE,
    COALESCE(TO_NUMBER(REPLACE(REPLACE("MIT_LIVINGWAGE".MINIMUM_WAGE, '$', ''), ',', '')), 0) AS MINIMUM_WAGE,
    COALESCE(TO_NUMBER(REPLACE(REPLACE("MIT_typicalexpenses".LIVING_EXPENSES, '$', ''), ',', '')), 0) AS LIVING_EXPENSES,
    COALESCE(TO_NUMBER(REPLACE(REPLACE("MIT_typicalannualsalaries"."Typical Annual Salary", '$', ''), ',', '')), 0) AS TYPICAL_ANNUAL__SALARY,
    "DIM_PROFESSION".PROFESSION_ID AS PROFESSION_ID,
    "DIM_LOCATION".LOCATION_ID AS LOCATION_ID,
    COALESCE(TO_NUMBER(REPLACE(REPLACE("SCHOOL_DATA".PUPILTEACHERRATIO, '$', ''), ',', '')), 0) AS PUPIL_TEACHER_RATIO,
    "DIM_SCHOOL".SCHOOL_ID AS SCHOOL_ID,
    COALESCE(TO_NUMBER(REPLACE(REPLACE("NYS_CRIME_DATA".POPULATION_NUM, '$', ''), ',', '')), 0) AS POPULATION_NUM,
    COALESCE(TO_NUMBER(REPLACE(REPLACE("NYS_CRIME_DATA".INDEX_TOTAL_COUNT, '$', ''), ',', '')), 0) AS INDEX_TOTAL_COUNT,
    COALESCE(TO_NUMBER(REPLACE(REPLACE("NYS_CRIME_DATA".VIOLENT_TOTAL_COUNT, '$', ''), ',', '')), 0) AS VIOLENT_TOTAL_COUNT,
    COALESCE("NYS_CRIME_DATA".MURDER_COUNT, 0) AS MURDER_COUNTRAPE_COUNT,
    COALESCE(TO_NUMBER(REPLACE(REPLACE("NYS_CRIME_DATA".ROBBERY_COUNT, '$', ''), ',', '')), 0) AS ROBBERY_COUNT,
    COALESCE(TO_NUMBER(REPLACE(REPLACE("NYS_CRIME_DATA".AGG_ASSAULT_COUNT, '$', ''), ',', '')), 0) AS AGGREVATED_ASSAULT_COUNT,
    COALESCE(TO_NUMBER(REPLACE(REPLACE("NYS_CRIME_DATA".PROPERTY_TOTAL_COUNT, '$', ''), ',', '')), 0) AS PROPERTY_TOTAL_COUNT,
    COALESCE(TO_NUMBER(REPLACE(REPLACE("NYS_CRIME_DATA".BURGLARY_COUNT, '$', ''), ',', '')), 0) AS BURGLARY_COUNT,
    COALESCE(TO_NUMBER(REPLACE(REPLACE("NYS_CRIME_DATA".LARCENY_COUNT, '$', ''), ',', '')), 0) AS LARCENY_COUNT,
    COALESCE(TO_NUMBER(REPLACE(REPLACE("NYS_CRIME_DATA".MV_THEFT_COUNT, '$', ''), ',', '')), 0) AS MV_THEFT_COUNT,
    COALESCE("SALES_HOUSING".BUILDING_ASSESSED_VALUE, 0) AS BUILDING_ASSESSED_VALUE,
    COALESCE("SALES_HOUSING".BUILDING_APPRAISED_VALUE, 0) AS BUILDING_APPRAISED_VALUE,
    COALESCE("SALES_HOUSING".SALE_PRICE, 0) AS SALE_PRICE,
    COALESCE("SALES_HOUSING".LAND_APPRAISED_VALUE, 0) AS LAND_APPRAISED_VALUE,
    COALESCE("SALES_HOUSING".LAND_ASSESSED_VALUE, 0) AS LAND_ASSESSED_VALUE,
    "SALES_HOUSING".SALE_ID AS SALE_ID,-- Added SALE_ID column
    "SALES_HOUSING".PROPERTY_ID AS PROPERTY_ID, -- Added PROPERTY_ID column
    "DIM_TIME".TIME_ID AS TIME_ID  -- Added TIME_ID column
FROM
    "MIT_LIVINGWAGE"
JOIN
    "MIT_typicalexpenses" ON "MIT_LIVINGWAGE".COUNTIES = "MIT_typicalexpenses"."Counties "
JOIN
    "MIT_typicalannualsalaries" ON "MIT_LIVINGWAGE".COUNTIES = "MIT_typicalannualsalaries"."Counties"
JOIN
    "DIM_PROFESSION" ON "MIT_typicalannualsalaries"."Occupational Area" = "DIM_PROFESSION".PROFESSION_TITLE
JOIN
    "DIM_LOCATION" ON "MIT_LIVINGWAGE".COUNTIES = "DIM_LOCATION".COUNTIES
LEFT JOIN
    "SCHOOL_DATA" ON "MIT_LIVINGWAGE".COUNTIES = "SCHOOL_DATA".COUNTY
LEFT JOIN
    "DIM_SCHOOL" ON "SCHOOL_DATA"."NAME" = "DIM_SCHOOL".SCHOOL_NAME
JOIN
    "NYS_CRIME_DATA" ON "MIT_LIVINGWAGE".COUNTIES = "NYS_CRIME_DATA"."County/Region"
JOIN
    "SALES_HOUSING" ON "DIM_LOCATION"."COUNTIES" = "SALES_HOUSING"."PROPERTY_COUNTY"
JOIN
    "DIM_TIME" ON "NYS_CRIME_DATA"."YEAR_NUM" = "DIM_TIME"."YEAR_NUM";