USE DATABASE HOUSING_CIS9440;
USE SCHEMA HOUSINGNY;

-- Populate dim_profession with unique professions from MIT_typicalannualsalaries
INSERT INTO dim_profession (PROFESSION_ID, PROFESSION_TITLE)
SELECT 
    ROW_NUMBER() OVER (ORDER BY "Occupational Area") AS PROFESSION_ID,
    "Occupational Area" AS PROFESSION_TITLE
FROM "MIT_typicalannualsalaries"
WHERE "Occupational Area" IS NOT NULL
GROUP BY "Occupational Area";

-- Insert unique counties into dim_location
INSERT INTO dim_location (LOCATION_ID, COUNTIES)
SELECT ROW_NUMBER() OVER (ORDER BY COUNTIES) AS LOCATION_ID, COUNTIES
FROM (
    SELECT DISTINCT COUNTIES FROM "MIT_LIVINGWAGE"
    UNION
    SELECT DISTINCT "Counties " FROM "MIT_typicalexpenses"
) AS counties_list;

CREATE SEQUENCE LOCATION_ID_SEQUENCE;

-- Insert unique counties into dim_location
INSERT INTO dim_location (LOCATION_ID, COUNTIES)
SELECT ROW_NUMBER() OVER (ORDER BY COUNTIES) AS LOCATION_ID, COUNTIES
FROM (
    SELECT DISTINCT COUNTIES FROM "MIT_LIVINGWAGE"
    UNION
    SELECT DISTINCT "Counties " FROM "MIT_typicalexpenses"
) AS counties_list;


-- Insert new rows into DIM_LOCATION for counties that do not exist
INSERT INTO HOUSING_CIS9440.HOUSINGNY.DIM_LOCATION (LOCATION_ID, COUNTIES, CITY, STATE_NAME, ZIP_CODE)
SELECT
    ROW_NUMBER() OVER (ORDER BY COUNTY) AS LOCATION_ID,
    COUNTY AS COUNTIES,
    CITY,
    STATE AS STATE_NAME,
    ZIP AS ZIP_CODE
FROM (
    SELECT DISTINCT COUNTY, CITY, STATE, ZIP
    FROM "SCHOOL_DATA"
    WHERE COUNTY IS NOT NULL
) sd
WHERE NOT EXISTS (
    SELECT 1
    FROM HOUSING_CIS9440.HOUSINGNY.DIM_LOCATION
    WHERE COUNTIES = sd.COUNTY
);

-- Update existing rows in DIM_LOCATION with CITY, STATE_NAME, and ZIP_CODE
UPDATE HOUSING_CIS9440.HOUSINGNY.DIM_LOCATION dim_loc
SET
    CITY = sd.CITY,
    STATE_NAME = sd.STATE,
    ZIP_CODE = sd.ZIP
FROM (
    SELECT DISTINCT COUNTY, CITY, STATE, ZIP
    FROM "SCHOOL_DATA"
    WHERE COUNTY IS NOT NULL
) sd
WHERE dim_loc.COUNTIES = sd.COUNTY;


-- clean crime data to match the names on the MIT Data and School Data
-- Update NYS_CRIME_DATA to include " County" in county names
UPDATE NYS_CRIME_DATA
SET "County/Region" = "County/Region" || ' County';
-- updtaing dim_location to add data from the crime data 
SELECT DISTINCT "County/Region" AS COUNTY
FROM HOUSING_CIS9440.HOUSINGNY.NYS_CRIME_DATA
WHERE "County/Region" IS NOT NULL;
-- Insert Missing Counties into DIM_LOCATION if they don't exist
SELECT DISTINCT "County/Region" AS COUNTY
FROM HOUSING_CIS9440.HOUSINGNY.NYS_CRIME_DATA
WHERE "County/Region" IS NOT NULL;
-- Insert new counties from NYS_CRIME_DATA into DIM_LOCATION if they don't exist
INSERT INTO HOUSING_CIS9440.HOUSINGNY.DIM_LOCATION (LOCATION_ID, COUNTIES)
SELECT
    ROW_NUMBER() OVER (ORDER BY COUNTY) AS LOCATION_ID,
    COUNTY AS COUNTIES
FROM (
    SELECT DISTINCT "County/Region" AS COUNTY
    FROM HOUSING_CIS9440.HOUSINGNY.NYS_CRIME_DATA
    WHERE "County/Region" IS NOT NULL
) nc
WHERE NOT EXISTS (
    SELECT 1
    FROM HOUSING_CIS9440.HOUSINGNY.DIM_LOCATION
    WHERE COUNTIES = nc.COUNTY
);

-- Update the PROPERTY_COUNTY column in SALES_HOUSING
UPDATE SALES_HOUSING
SET PROPERTY_COUNTY = INITCAP(PROPERTY_COUNTY) || ' County';

-- Insert new counties into DIM_LOCATION if they don't exist
INSERT INTO HOUSING_CIS9440.HOUSINGNY.DIM_LOCATION (LOCATION_ID, COUNTIES, CITY, STATE_NAME, ZIP_CODE)
SELECT
    ROW_NUMBER() OVER (ORDER BY PROPERTY_COUNTY) AS LOCATION_ID,
    PROPERTY_COUNTY AS COUNTIES,
    PROPERTY_CITY AS CITY,
    STATE AS STATE_NAME,
    PROPERTY_ZIP5 AS ZIP_CODE
FROM (
    SELECT DISTINCT PROPERTY_COUNTY, PROPERTY_CITY, STATE, PROPERTY_ZIP5
    FROM HOUSING_CIS9440.HOUSINGNY.SALES_HOUSING
    WHERE PROPERTY_COUNTY IS NOT NULL
) sh
WHERE NOT EXISTS (
    SELECT 1
    FROM HOUSING_CIS9440.HOUSINGNY.DIM_LOCATION
    WHERE COUNTIES = sh.PROPERTY_COUNTY
);

-- Update existing records in DIM_LOCATION with CITY, STATE_NAME, and ZIP_CODE
UPDATE HOUSING_CIS9440.HOUSINGNY.DIM_LOCATION dim_loc
SET
    CITY = sh.PROPERTY_CITY,
    STATE_NAME = sh.STATE,
    ZIP_CODE = sh.PROPERTY_ZIP5
FROM (
    SELECT DISTINCT PROPERTY_COUNTY, PROPERTY_CITY, STATE, PROPERTY_ZIP5
    FROM HOUSING_CIS9440.HOUSINGNY.SALES_HOUSING
    WHERE PROPERTY_COUNTY IS NOT NULL
) sh
WHERE dim_loc.COUNTIES = sh.PROPERTY_COUNTY;
-- Insert new counties into DIM_LOCATION if they don't exist
INSERT INTO HOUSING_CIS9440.HOUSINGNY.DIM_LOCATION (LOCATION_ID, COUNTIES, CITY, STATE_NAME, ZIP_CODE, STREET_ADDRESS)
SELECT
    ROW_NUMBER() OVER (ORDER BY PROPERTY_COUNTY) AS LOCATION_ID,
    PROPERTY_COUNTY AS COUNTIES,
    PROPERTY_CITY AS CITY,
    STATE AS STATE_NAME,
    PROPERTY_ZIP5 AS ZIP_CODE,
    PROPERTY_STREET_ADDRESS AS STREET_ADDRESS
FROM (
    SELECT DISTINCT PROPERTY_COUNTY, PROPERTY_CITY, STATE, PROPERTY_ZIP5, PROPERTY_STREET_ADDRESS
    FROM HOUSING_CIS9440.HOUSINGNY.SALES_HOUSING
    WHERE PROPERTY_COUNTY IS NOT NULL
) sh
WHERE NOT EXISTS (
    SELECT 1
    FROM HOUSING_CIS9440.HOUSINGNY.DIM_LOCATION
    WHERE COUNTIES = sh.PROPERTY_COUNTY
);

-- Update existing records in DIM_LOCATION with CITY, STATE_NAME, ZIP_CODE, and STREET_ADDRESS
UPDATE HOUSING_CIS9440.HOUSINGNY.DIM_LOCATION dim_loc
SET
    CITY = sh.PROPERTY_CITY,
    STATE_NAME = sh.STATE,
    ZIP_CODE = sh.PROPERTY_ZIP5,
    STREET_ADDRESS = sh.PROPERTY_STREET_ADDRESS
FROM (
    SELECT DISTINCT PROPERTY_COUNTY, PROPERTY_CITY, STATE, PROPERTY_ZIP5, PROPERTY_STREET_ADDRESS
    FROM HOUSING_CIS9440.HOUSINGNY.SALES_HOUSING
    WHERE PROPERTY_COUNTY IS NOT NULL
) sh
WHERE dim_loc.COUNTIES = sh.PROPERTY_COUNTY;


-- Create or replace sequence for generating FACTS_ID
CREATE OR REPLACE SEQUENCE FACTS_ID_SEQUENCE;

-- Insert data into facts_housing using the sequence to generate FACTS_ID
INSERT INTO HOUSING_CIS9440.HOUSINGNY.FACTS_HOUSING (
    FACTS_ID,
    LIVING_WAGE,
    POVERTY_WAGE,
    MINIMUM_WAGE,
    LIVING_EXPENSES,
    TYPICAL_ANNUAL__SALARY,
    PROFESSION_ID,
    LOCATION_ID,
    PUPIL_TEACHER_RATIO,
    SCHOOL_ID,
    POPULATION_NUM,
    INDEX_TOTAL_COUNT,
    VIOLENT_TOTAL_COUNT,
    MURDER_COUNTRAPE_COUNT,
    ROBBERY_COUNT,
    AGGREVATED_ASSAULT_COUNT,
    PROPERTY_TOTAL_COUNT,
    BURGLARY_COUNT,
    LARCENY_COUNT,
    MV_THEFT_COUNT,
    BUILDING_ASSESSED_VALUE,
    BUILDING_APPRAISED_VALUE,
    SALE_PRICE,
    LAND_APPRAISED_VALUE,
    LAND_ASSESSED_VALUE,
    SALE_ID,
    PROPERTY_ID,
    TIME_ID  -- Added SALE_ID and TIME_ID columns
)
SELECT
    FACTS_ID_SEQUENCE.NEXTVAL AS FACTS_ID,
    COALESCE(TO_NUMBER(REPLACE(REPLACE("MIT_LIVINGWAGE".LIVING_WAGE, '$', ''), ',', '')), 0) AS LIVING_WAGE,
    COALESCE(TO_NUMBER(REPLACE(REPLACE("MIT_LIVINGWAGE".POVERTY_WAGE, '$', ''), ',', '')), 0) AS POVERTY_WAGE,
    COALESCE(TO_NUMBER(REPLACE(REPLACE("MIT_LIVINGWAGE".MINIMUM_WAGE, '$', ''), ',', '')), 0) AS MINIMUM_WAGE,
    COALESCE(TO_NUMBER(REPLACE(REPLACE("MIT_typicalexpenses".LIVING_EXPENSES, '$', ''), ',', '')), 0) AS LIVING_EXPENSES,
    COALESCE(TO_NUMBER(REPLACE(REPLACE("MIT_typicalannualsalaries"."Typical Annual Salary", '$', ''), ',', '')), 0) AS TYPICAL_ANNUAL__SALARY,
    "DIM_PROFESSION".PROFESSION_ID AS PROFESSION_ID,
    "DIM_LOCATION".LOCATION_ID AS LOCATION_ID,
    COALESCE(TO_NUMBER(REPLACE(REPLACE("SCHOOL_DATA".PUPILTEACHERRATIO, '$', ''), ',', '')), 0) AS PUPIL_TEACHER_RATIO,
    "DIM_SCHOOL".SCHOOL_ID AS SCHOOL_ID,
    COALESCE(TO_NUMBER(REPLACE(REPLACE("NYS_CRIME_DATA".POPULATION_NUM, '$', ''), ',', '')), 0) AS POPULATION_NUM,
    COALESCE(TO_NUMBER(REPLACE(REPLACE("NYS_CRIME_DATA".INDEX_TOTAL_COUNT, '$', ''), ',', '')), 0) AS INDEX_TOTAL_COUNT,
    COALESCE(TO_NUMBER(REPLACE(REPLACE("NYS_CRIME_DATA".VIOLENT_TOTAL_COUNT, '$', ''), ',', '')), 0) AS VIOLENT_TOTAL_COUNT,
    COALESCE("NYS_CRIME_DATA".MURDER_COUNT, 0) AS MURDER_COUNTRAPE_COUNT,
    COALESCE(TO_NUMBER(REPLACE(REPLACE("NYS_CRIME_DATA".ROBBERY_COUNT, '$', ''), ',', '')), 0) AS ROBBERY_COUNT,
    COALESCE(TO_NUMBER(REPLACE(REPLACE("NYS_CRIME_DATA".AGG_ASSAULT_COUNT, '$', ''), ',', '')), 0) AS AGGREVATED_ASSAULT_COUNT,
    COALESCE(TO_NUMBER(REPLACE(REPLACE("NYS_CRIME_DATA".PROPERTY_TOTAL_COUNT, '$', ''), ',', '')), 0) AS PROPERTY_TOTAL_COUNT,
    COALESCE(TO_NUMBER(REPLACE(REPLACE("NYS_CRIME_DATA".BURGLARY_COUNT, '$', ''), ',', '')), 0) AS BURGLARY_COUNT,
    COALESCE(TO_NUMBER(REPLACE(REPLACE("NYS_CRIME_DATA".LARCENY_COUNT, '$', ''), ',', '')), 0) AS LARCENY_COUNT,
    COALESCE(TO_NUMBER(REPLACE(REPLACE("NYS_CRIME_DATA".MV_THEFT_COUNT, '$', ''), ',', '')), 0) AS MV_THEFT_COUNT,
    COALESCE("SALES_HOUSING".BUILDING_ASSESSED_VALUE, 0) AS BUILDING_ASSESSED_VALUE,
    COALESCE("SALES_HOUSING".BUILDING_APPRAISED_VALUE, 0) AS BUILDING_APPRAISED_VALUE,
    COALESCE("SALES_HOUSING".SALE_PRICE, 0) AS SALE_PRICE,
    COALESCE("SALES_HOUSING".LAND_APPRAISED_VALUE, 0) AS LAND_APPRAISED_VALUE,
    COALESCE("SALES_HOUSING".LAND_ASSESSED_VALUE, 0) AS LAND_ASSESSED_VALUE,
    "SALES_HOUSING".SALE_ID AS SALE_ID,-- Added SALE_ID column
    "SALES_HOUSING".PROPERTY_ID AS PROPERTY_ID, -- ADDED PROPERTY_ID column
    "DIM_TIME".TIME_ID AS TIME_ID  -- Added TIME_ID column
FROM
    "MIT_LIVINGWAGE"
JOIN
    "MIT_typicalexpenses" ON "MIT_LIVINGWAGE".COUNTIES = "MIT_typicalexpenses"."Counties "
JOIN
    "MIT_typicalannualsalaries" ON "MIT_LIVINGWAGE".COUNTIES = "MIT_typicalannualsalaries"."Counties"
JOIN
    "DIM_PROFESSION" ON "MIT_typicalannualsalaries"."Occupational Area" = "DIM_PROFESSION".PROFESSION_TITLE
JOIN
    "DIM_LOCATION" ON "MIT_LIVINGWAGE".COUNTIES = "DIM_LOCATION".COUNTIES
LEFT JOIN
    "SCHOOL_DATA" ON "MIT_LIVINGWAGE".COUNTIES = "SCHOOL_DATA".COUNTY
LEFT JOIN
    "DIM_SCHOOL" ON "SCHOOL_DATA"."NAME" = "DIM_SCHOOL".SCHOOL_NAME
JOIN
    "NYS_CRIME_DATA" ON "MIT_LIVINGWAGE".COUNTIES = "NYS_CRIME_DATA"."County/Region"
JOIN
    "SALES_HOUSING" ON "DIM_LOCATION"."COUNTIES" = "SALES_HOUSING"."PROPERTY_COUNTY"
JOIN
    "DIM_TIME" ON "NYS_CRIME_DATA"."YEAR_NUM" = "DIM_TIME"."YEAR_NUM";  -- Joined DIM_TIME to retrieve TIME_ID