USE DATABASE HOUSING_CIS9440;
USE SCHEMA HOUSINGNY;

INSERT INTO HOUSING_CIS9440.HOUSINGNY.DIM_TIME (
    TIME_ID,
    YEAR_NUM
)
SELECT
    ROW_NUMBER() OVER (ORDER BY YEAR_NUM) AS TIME_ID,
    YEAR_NUM AS YEAR_NUM
FROM 
    HOUSING_CIS9440.HOUSINGNY.NYS_CRIME_DATA;