USE DATABASE HOUSING_CIS9440;
USE SCHEMA HOUSINGNY;

-- Insert unique counties into dim_location
INSERT INTO dim_location (LOCATION_ID, COUNTIES)
SELECT ROW_NUMBER() OVER (ORDER BY COUNTIES) AS LOCATION_ID, COUNTIES
FROM (
    SELECT DISTINCT COUNTIES FROM "MIT_LIVINGWAGE"
    UNION
    SELECT DISTINCT "Counties " FROM "MIT_typicalexpenses"
) AS counties_list;

CREATE SEQUENCE LOCATION_ID_SEQUENCE;

-- Insert unique counties into dim_location
INSERT INTO dim_location (LOCATION_ID, COUNTIES)
SELECT ROW_NUMBER() OVER (ORDER BY COUNTIES) AS LOCATION_ID, COUNTIES
FROM (
    SELECT DISTINCT COUNTIES FROM "MIT_LIVINGWAGE"
    UNION
    SELECT DISTINCT "Counties " FROM "MIT_typicalexpenses"
) AS counties_list;


-- Insert new rows into DIM_LOCATION for counties that do not exist
INSERT INTO HOUSING_CIS9440.HOUSINGNY.DIM_LOCATION (LOCATION_ID, COUNTIES, CITY, STATE_NAME, ZIP_CODE)
SELECT
    ROW_NUMBER() OVER (ORDER BY COUNTY) AS LOCATION_ID,
    COUNTY AS COUNTIES,
    CITY,
    STATE AS STATE_NAME,
    ZIP AS ZIP_CODE
FROM (
    SELECT DISTINCT COUNTY, CITY, STATE, ZIP
    FROM "SCHOOL_DATA"
    WHERE COUNTY IS NOT NULL
) sd
WHERE NOT EXISTS (
    SELECT 1
    FROM HOUSING_CIS9440.HOUSINGNY.DIM_LOCATION
    WHERE COUNTIES = sd.COUNTY
);

-- Update existing rows in DIM_LOCATION with CITY, STATE_NAME, and ZIP_CODE
UPDATE HOUSING_CIS9440.HOUSINGNY.DIM_LOCATION dim_loc
SET
    CITY = sd.CITY,
    STATE_NAME = sd.STATE,
    ZIP_CODE = sd.ZIP
FROM (
    SELECT DISTINCT COUNTY, CITY, STATE, ZIP
    FROM "SCHOOL_DATA"
    WHERE COUNTY IS NOT NULL
) sd
WHERE dim_loc.COUNTIES = sd.COUNTY;


-- clean crime data to match the names on the MIT Data and School Data
-- Update NYS_CRIME_DATA to include " County" in county names
UPDATE NYS_CRIME_DATA
SET "County/Region" = "County/Region" || ' County';
-- updtaing dim_location to add data from the crime data 
SELECT DISTINCT "County/Region" AS COUNTY
FROM HOUSING_CIS9440.HOUSINGNY.NYS_CRIME_DATA
WHERE "County/Region" IS NOT NULL;
-- Insert Missing Counties into DIM_LOCATION if they don't exist
SELECT DISTINCT "County/Region" AS COUNTY
FROM HOUSING_CIS9440.HOUSINGNY.NYS_CRIME_DATA
WHERE "County/Region" IS NOT NULL;
-- Insert new counties from NYS_CRIME_DATA into DIM_LOCATION if they don't exist
INSERT INTO HOUSING_CIS9440.HOUSINGNY.DIM_LOCATION (LOCATION_ID, COUNTIES)
SELECT
    ROW_NUMBER() OVER (ORDER BY COUNTY) AS LOCATION_ID,
    COUNTY AS COUNTIES
FROM (
    SELECT DISTINCT "County/Region" AS COUNTY
    FROM HOUSING_CIS9440.HOUSINGNY.NYS_CRIME_DATA
    WHERE "County/Region" IS NOT NULL
) nc
WHERE NOT EXISTS (
    SELECT 1
    FROM HOUSING_CIS9440.HOUSINGNY.DIM_LOCATION
    WHERE COUNTIES = nc.COUNTY
);

-- Update the PROPERTY_COUNTY column in SALES_HOUSING
UPDATE SALES_HOUSING
SET PROPERTY_COUNTY = INITCAP(PROPERTY_COUNTY) || ' County';

-- Insert new counties into DIM_LOCATION if they don't exist
INSERT INTO HOUSING_CIS9440.HOUSINGNY.DIM_LOCATION (LOCATION_ID, COUNTIES, CITY, STATE_NAME, ZIP_CODE)
SELECT
    ROW_NUMBER() OVER (ORDER BY PROPERTY_COUNTY) AS LOCATION_ID,
    PROPERTY_COUNTY AS COUNTIES,
    PROPERTY_CITY AS CITY,
    STATE AS STATE_NAME,
    PROPERTY_ZIP5 AS ZIP_CODE
FROM (
    SELECT DISTINCT PROPERTY_COUNTY, PROPERTY_CITY, STATE, PROPERTY_ZIP5
    FROM HOUSING_CIS9440.HOUSINGNY.SALES_HOUSING
    WHERE PROPERTY_COUNTY IS NOT NULL
) sh
WHERE NOT EXISTS (
    SELECT 1
    FROM HOUSING_CIS9440.HOUSINGNY.DIM_LOCATION
    WHERE COUNTIES = sh.PROPERTY_COUNTY
);

-- Update existing records in DIM_LOCATION with CITY, STATE_NAME, and ZIP_CODE
UPDATE HOUSING_CIS9440.HOUSINGNY.DIM_LOCATION dim_loc
SET
    CITY = sh.PROPERTY_CITY,
    STATE_NAME = sh.STATE,
    ZIP_CODE = sh.PROPERTY_ZIP5
FROM (
    SELECT DISTINCT PROPERTY_COUNTY, PROPERTY_CITY, STATE, PROPERTY_ZIP5
    FROM HOUSING_CIS9440.HOUSINGNY.SALES_HOUSING
    WHERE PROPERTY_COUNTY IS NOT NULL
) sh
WHERE dim_loc.COUNTIES = sh.PROPERTY_COUNTY;
-- Insert new counties into DIM_LOCATION if they don't exist
INSERT INTO HOUSING_CIS9440.HOUSINGNY.DIM_LOCATION (LOCATION_ID, COUNTIES, CITY, STATE_NAME, ZIP_CODE, STREET_ADDRESS)
SELECT
    ROW_NUMBER() OVER (ORDER BY PROPERTY_COUNTY) AS LOCATION_ID,
    PROPERTY_COUNTY AS COUNTIES,
    PROPERTY_CITY AS CITY,
    STATE AS STATE_NAME,
    PROPERTY_ZIP5 AS ZIP_CODE,
    PROPERTY_STREET_ADDRESS AS STREET_ADDRESS
FROM (
    SELECT DISTINCT PROPERTY_COUNTY, PROPERTY_CITY, STATE, PROPERTY_ZIP5, PROPERTY_STREET_ADDRESS
    FROM HOUSING_CIS9440.HOUSINGNY.SALES_HOUSING
    WHERE PROPERTY_COUNTY IS NOT NULL
) sh
WHERE NOT EXISTS (
    SELECT 1
    FROM HOUSING_CIS9440.HOUSINGNY.DIM_LOCATION
    WHERE COUNTIES = sh.PROPERTY_COUNTY
);

-- Update existing records in DIM_LOCATION with CITY, STATE_NAME, ZIP_CODE, and STREET_ADDRESS
UPDATE HOUSING_CIS9440.HOUSINGNY.DIM_LOCATION dim_loc
SET
    CITY = sh.PROPERTY_CITY,
    STATE_NAME = sh.STATE,
    ZIP_CODE = sh.PROPERTY_ZIP5,
    STREET_ADDRESS = sh.PROPERTY_STREET_ADDRESS
FROM (
    SELECT DISTINCT PROPERTY_COUNTY, PROPERTY_CITY, STATE, PROPERTY_ZIP5, PROPERTY_STREET_ADDRESS
    FROM HOUSING_CIS9440.HOUSINGNY.SALES_HOUSING
    WHERE PROPERTY_COUNTY IS NOT NULL
) sh
WHERE dim_loc.COUNTIES = sh.PROPERTY_COUNTY;