-- Insert a single row for the year 2022 into DIM_TIME
INSERT INTO HOUSING_CIS9440.HOUSINGNY.DIM_TIME (
    TIME_ID,
    YEAR_NUM
)
SELECT
    1 AS TIME_ID,
    2022 AS YEAR_NUM
FROM
    (SELECT DISTINCT "Year" FROM HOUSING_CIS9440.HOUSINGNY.NYS_CRIME_DATA);