USE DATABASE HOUSING_CIS9440;
USE SCHEMA HOUSINGNY;

-- Populate dim_profession with unique professions from MIT_typicalannualsalaries
INSERT INTO dim_profession (PROFESSION_ID, PROFESSION_TITLE)
SELECT 
    ROW_NUMBER() OVER (ORDER BY "Occupational Area") AS PROFESSION_ID,
    "Occupational Area" AS PROFESSION_TITLE
FROM "MIT_typicalannualsalaries"
WHERE "Occupational Area" IS NOT NULL
GROUP BY "Occupational Area";

-- Insert unique counties into dim_location
INSERT INTO dim_location (LOCATION_ID, COUNTIES)
SELECT ROW_NUMBER() OVER (ORDER BY COUNTIES) AS LOCATION_ID, COUNTIES
FROM (
    SELECT DISTINCT COUNTIES FROM "MIT_LIVINGWAGE"
    UNION
    SELECT DISTINCT "Counties " FROM "MIT_typicalexpenses"
) AS counties_list;

-- updtaing dim_location to add data from the school_data 
CREATE SEQUENCE LOCATION_ID_SEQUENCE;

-- Insert new rows into DIM_LOCATION for counties that do not exist
INSERT INTO HOUSING_CIS9440.HOUSINGNY.DIM_LOCATION (LOCATION_ID, COUNTIES, CITY, STATE_NAME, ZIP_CODE)
SELECT
    ROW_NUMBER() OVER (ORDER BY COUNTY) AS LOCATION_ID,
    COUNTY AS COUNTIES,
    CITY,
    STATE AS STATE_NAME,
    ZIP AS ZIP_CODE
FROM (
    SELECT DISTINCT COUNTY, CITY, STATE, ZIP
    FROM "SCHOOL_DATA"
    WHERE COUNTY IS NOT NULL
) sd
WHERE NOT EXISTS (
    SELECT 1
    FROM HOUSING_CIS9440.HOUSINGNY.DIM_LOCATION
    WHERE COUNTIES = sd.COUNTY
);

-- Update existing rows in DIM_LOCATION with CITY, STATE_NAME, and ZIP_CODE
UPDATE HOUSING_CIS9440.HOUSINGNY.DIM_LOCATION dim_loc
SET
    CITY = sd.CITY,
    STATE_NAME = sd.STATE,
    ZIP_CODE = sd.ZIP
FROM (
    SELECT DISTINCT COUNTY, CITY, STATE, ZIP
    FROM "SCHOOL_DATA"
    WHERE COUNTY IS NOT NULL
) sd
WHERE dim_loc.COUNTIES = sd.COUNTY;

-- clean crime data to match the names on the MIT Data and School Data
-- Update NYS_CRIME_DATA to include " County" in county names
UPDATE NYS_CRIME_DATA
SET "County/Region" = "County/Region" || ' County';
-- - updtaing dim_location to add data from the crime data 


-- Create or replace sequence for generating FACTS_ID
CREATE OR REPLACE SEQUENCE FACTS_ID_SEQUENCE;

-- Insert data into facts_housing using the sequence to generate FACTS_ID
INSERT INTO HOUSING_CIS9440.HOUSINGNY.FACTS_HOUSING (
    FACTS_ID,
    LIVING_WAGE,
    POVERTY_WAGE,
    MINIMUM_WAGE,
    LIVING_EXPENSES,
    TYPICAL_ANNUAL__SALARY,
    PROFESSION_ID,
    LOCATION_ID,
    PUPIL_TEACHER_RATIO,
    SCHOOL_ID,
    POPULATION_NUM,
    INDEX_TOTAL_COUNT,
    VIOLENT_TOTAL_COUNT,
    MURDER_COUNTRAPE_COUNT,
    ROBBERY_COUNT,
    AGGREVATED_ASSAULT_COUNT,
    PROPERTY_TOTAL_COUNT,
    BURGLARY_COUNT,
    LARCENY_COUNT,
    MV_THEFT_COUNT
)
SELECT
    FACTS_ID_SEQUENCE.NEXTVAL AS FACTS_ID,
    COALESCE(TO_NUMBER(REPLACE(REPLACE("MIT_LIVINGWAGE".LIVING_WAGE, '$', ''), ',', '')), 0) AS LIVING_WAGE,
    COALESCE(TO_NUMBER(REPLACE(REPLACE("MIT_LIVINGWAGE".POVERTY_WAGE, '$', ''), ',', '')), 0) AS POVERTY_WAGE,
    COALESCE(TO_NUMBER(REPLACE(REPLACE("MIT_LIVINGWAGE".MINIMUM_WAGE, '$', ''), ',', '')), 0) AS MINIMUM_WAGE,
    COALESCE(TO_NUMBER(REPLACE(REPLACE("MIT_typicalexpenses".LIVING_EXPENSES, '$', ''), ',', '')), 0) AS LIVING_EXPENSES,
    COALESCE(TO_NUMBER(REPLACE(REPLACE("MIT_typicalannualsalaries"."Typical Annual Salary", '$', ''), ',', '')), 0) AS TYPICAL_ANNUAL__SALARY,
    "DIM_PROFESSION".PROFESSION_ID AS PROFESSION_ID,
    "DIM_LOCATION".LOCATION_ID AS LOCATION_ID,
    COALESCE(TO_NUMBER(REPLACE(REPLACE("SCHOOL_DATA".PUPILTEACHERRATIO, '$', ''), ',', '')), 0) AS PUPIL_TEACHER_RATIO,
    "DIM_SCHOOL".SCHOOL_ID AS SCHOOL_ID,
    COALESCE(TO_NUMBER(REPLACE(REPLACE("NYS_CRIME_DATA".POPULATION_NUM, '$', ''), ',', '')), 0) AS POPULATION_NUM,
    COALESCE(TO_NUMBER(REPLACE(REPLACE("NYS_CRIME_DATA".INDEX_TOTAL_COUNT, '$', ''), ',', '')), 0) AS INDEX_TOTAL_COUNT,
    COALESCE(TO_NUMBER(REPLACE(REPLACE("NYS_CRIME_DATA".VIOLENT_TOTAL_COUNT, '$', ''), ',', '')), 0) AS VIOLENT_TOTAL_COUNT,
    COALESCE("NYS_CRIME_DATA".MURDER_COUNT, 0) AS MURDER_COUNTRAPE_COUNT,
    COALESCE(TO_NUMBER(REPLACE(REPLACE("NYS_CRIME_DATA".ROBBERY_COUNT, '$', ''), ',', '')), 0) AS ROBBERY_COUNT,
    COALESCE(TO_NUMBER(REPLACE(REPLACE("NYS_CRIME_DATA".AGG_ASSAULT_COUNT, '$', ''), ',', '')), 0) AS AGGREVATED_ASSAULT_COUNT,
    COALESCE(TO_NUMBER(REPLACE(REPLACE("NYS_CRIME_DATA".PROPERTY_TOTAL_COUNT, '$', ''), ',', '')), 0) AS PROPERTY_TOTAL_COUNT,
    COALESCE(TO_NUMBER(REPLACE(REPLACE("NYS_CRIME_DATA".BURGLARY_COUNT, '$', ''), ',', '')), 0) AS BURGLARY_COUNT,
    COALESCE(TO_NUMBER(REPLACE(REPLACE("NYS_CRIME_DATA".LARCENY_COUNT, '$', ''), ',', '')), 0) AS LARCENY_COUNT,
    COALESCE(TO_NUMBER(REPLACE(REPLACE("NYS_CRIME_DATA".MV_THEFT_COUNT, '$', ''), ',', '')), 0) AS MV_THEFT_COUNT
FROM
    "MIT_LIVINGWAGE"
JOIN
    "MIT_typicalexpenses" ON "MIT_LIVINGWAGE".COUNTIES = "MIT_typicalexpenses"."Counties "
JOIN
    "MIT_typicalannualsalaries" ON "MIT_LIVINGWAGE".COUNTIES = "MIT_typicalannualsalaries"."Counties"
JOIN
    "DIM_PROFESSION" ON "MIT_typicalannualsalaries"."Occupational Area" = "DIM_PROFESSION".PROFESSION_TITLE
JOIN
    "DIM_LOCATION" ON "MIT_LIVINGWAGE".COUNTIES = "DIM_LOCATION".COUNTIES
LEFT JOIN
    "SCHOOL_DATA" ON "MIT_LIVINGWAGE".COUNTIES = "SCHOOL_DATA".COUNTY
LEFT JOIN
    "DIM_SCHOOL" ON "SCHOOL_DATA"."NAME" = "DIM_SCHOOL".SCHOOL_NAME
JOIN
    "NYS_CRIME_DATA" ON "MIT_LIVINGWAGE".COUNTIES = "NYS_CRIME_DATA"."County/Region";