INSERT INTO DIM_PROPERTY (PROPERTY_ID, PROPERTY_ZIP5, PROPERTY_STREET_ADDRESS, PROPERTY_CITY, PROPERTY_COUNTY, STATE, PROPERTY_TYPE, SALE_PRICE)
SELECT PROPERTY_ID, PROPERTY_ZIP5, PROPERTY_STREET_ADDRESS, PROPERTY_CITY, PROPERTY_COUNTY, STATE, PROPERTY_TYPE, SALE_PRICE
FROM SALES_HOUSING;